#!/usr/bin/env python3
"""Count semantic pages or checkpoints in common slide artifacts.

The command deliberately distinguishes talk-level semantic pages from Manim
Slides checkpoints.  Human output is a single integer for shell/agent use;
``--json`` includes the detected metric and artifact type.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class CountResult:
    count: int
    metric: str
    artifact_type: str
    source: str


def _numbering_manifest(payload: Any, source: Path) -> CountResult | None:
    if not isinstance(payload, dict):
        return None
    total = payload.get("total")
    if isinstance(total, int) and total >= 0 and any(
        key in payload for key in ("units", "sections", "chapters", "scope_contract")
    ):
        return CountResult(total, "semantic_pages", "numbering_manifest", str(source))
    return None


def _manim_json(payload: Any, source: Path) -> CountResult | None:
    if not isinstance(payload, dict):
        return None
    slides = payload.get("slides")
    if isinstance(slides, list):
        return CountResult(len(slides), "checkpoints", "manim_slides_json", str(source))
    # Older manim-slides metadata uses a scene name mapped to a slide list.
    lists = [value for value in payload.values() if isinstance(value, list)]
    if len(lists) == 1:
        return CountResult(len(lists[0]), "checkpoints", "manim_slides_json", str(source))
    return None


def count_json(path: Path) -> CountResult:
    payload = json.loads(path.read_text(encoding="utf-8"))
    result = _numbering_manifest(payload, path) or _manim_json(payload, path)
    if result is None:
        raise ValueError("JSON is neither a numbering manifest nor Manim Slides metadata")
    return result


def count_html(path: Path) -> CountResult:
    text = path.read_text(encoding="utf-8", errors="replace")
    # Reveal.js sections generated by manim-slides carry one background video
    # per checkpoint.  Count attributes, not asset filenames, to preserve order
    # and handle repeated assets.
    count = len(re.findall(r"\bdata-background-video\s*=", text, flags=re.IGNORECASE))
    if count == 0:
        raise ValueError("no Manim Slides checkpoint sections found in HTML")
    return CountResult(count, "checkpoints", "manim_slides_html", str(path))


def count_pptx(path: Path) -> CountResult:
    with zipfile.ZipFile(path) as archive:
        names = archive.namelist()
    count = sum(bool(re.fullmatch(r"ppt/slides/slide\d+\.xml", name)) for name in names)
    if count == 0:
        raise ValueError("PPTX contains no slide XML files")
    return CountResult(count, "slides", "pptx", str(path))


def count_pdf(path: Path) -> CountResult:
    try:
        from pypdf import PdfReader  # type: ignore

        count = len(PdfReader(str(path)).pages)
    except ImportError:
        completed = subprocess.run(
            ["pdfinfo", str(path)], capture_output=True, text=True, check=True
        )
        match = re.search(r"^Pages:\s+(\d+)\s*$", completed.stdout, flags=re.MULTILINE)
        if not match:
            raise ValueError("pdfinfo did not report a page count")
        count = int(match.group(1))
    return CountResult(count, "pages", "pdf", str(path))


def count_artifact(path: Path) -> CountResult:
    if not path.is_file():
        raise FileNotFoundError(path)
    suffix = path.suffix.lower()
    counters = {
        ".json": count_json,
        ".html": count_html,
        ".htm": count_html,
        ".pdf": count_pdf,
        ".pptx": count_pptx,
    }
    try:
        counter = counters[suffix]
    except KeyError as error:
        raise ValueError(f"unsupported slide artifact: {suffix or '<no suffix>'}") from error
    return counter(path)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Count pages/checkpoints without conflating the two metrics."
    )
    parser.add_argument("artifact", type=Path)
    parser.add_argument("--json", action="store_true", dest="as_json")
    args = parser.parse_args()
    try:
        result = count_artifact(args.artifact.expanduser().resolve())
    except (FileNotFoundError, ValueError, json.JSONDecodeError, zipfile.BadZipFile,
            subprocess.CalledProcessError) as error:
        print(f"count_slide_pages: {error}", file=sys.stderr)
        return 2
    if args.as_json:
        print(json.dumps(asdict(result), ensure_ascii=False, sort_keys=True))
    else:
        print(result.count)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
